#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/293ba572-645b-4581-bb49-e6912773a493/ # 
title: American Flights API

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
  post:

  /{ID}:
    get: